// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7AvxdZVux5zEg3Sy82zlGLANttFMG45E',
    appId: '1:360178124684:web:a9a1180c42ee9ed1ae78a9',
    messagingSenderId: '360178124684',
    projectId: 'gerenciamento-fila',
    authDomain: 'gerenciamento-fila.firebaseapp.com',
    storageBucket: 'gerenciamento-fila.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH6LDyeaMnxq98TDTHUBvnGJrOupN50N4',
    appId: '1:360178124684:android:733abbf3c359cbafae78a9',
    messagingSenderId: '360178124684',
    projectId: 'gerenciamento-fila',
    storageBucket: 'gerenciamento-fila.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB981aEW7v7VJuCW6-0of3SNJgEfpYmr88',
    appId: '1:360178124684:ios:8a216f293fb8d34cae78a9',
    messagingSenderId: '360178124684',
    projectId: 'gerenciamento-fila',
    storageBucket: 'gerenciamento-fila.appspot.com',
    iosClientId: '360178124684-eiahganhvr7cm9gk5uvgnn1se1j87r9u.apps.googleusercontent.com',
    iosBundleId: 'yes',
  );
}
